<a href="https://colab.research.google.com/github/uwtintres/robotic_surgeries/blob/main/Enthropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

def calc_enthropy(evaluation_matrix):
  row_size = len(evaluation_matrix)
  col_size = len(evaluation_matrix[0])
  h = -0.621335
  entropy_matrix = np.empty(shape=(row_size, col_size))
  weight_vector = np.empty(shape=(1, col_size))
  diversification = np.empty(shape=(1, col_size))
  col_sum = np.empty(shape=(1, col_size))
  for j in range(col_size):
    cursum = 0
    for i in range(row_size):
      cursum += evaluation_matrix[i][j]
    col_sum[0, j] = cursum
  print("col_sum", col_sum)
  for i in range(row_size):
    for j in range(col_size):
      entropy_matrix[i,j] = evaluation_matrix[i][j] / col_sum[0, j]
  print("entropy_matrix", entropy_matrix)
  for i in range(row_size):
    for j in range(col_size):
      entropy_matrix[i,j] = np.log(entropy_matrix[i,j]) * entropy_matrix[i,j]
  print("entropy_matrix", entropy_matrix)
  for j in range(col_size):
    cur_col_sum = sum(entropy_matrix[:, j])
    diversification[0, j] = 1 - cur_col_sum * h
  print("diversification", diversification)
  for j in range(col_size):
    weight_vector[0, j] = diversification[0, j] / sum(diversification[0, :])
  print("weight_vector", weight_vector)
  return weight_vector

In [24]:
import numpy as np
import pandas as pd 

xl = pd.read_excel("Fuzzy test.xlsx", sheet_name="Sheet2")
xl = pd.read_excel("Fuzzy test.xlsx", sheet_name="Sheet2", 
                   usecols=range(1, len(xl.columns)+1))

# initializing input matrix, weights, criterias
input_matrix = xl.tail(n=len(xl.index) - 2).values.tolist()
weights = xl.loc[0].values
criterias = xl.head(n=0).columns.values
new_criterias = []
for criteria in criterias:
  # if the attribute is non beneficiary, meaning min value is better -> False, 
  # otherwise, the criteria is True
  new_criterias.append(False if criteria[0] == 'N' else True)
print('input matrix: ', input_matrix)
print('weights: ', weights)
print('criterias: ', new_criterias)
# creating Topsis instance with the values above


input matrix:  [[250, 16, 12, 5], [200, 16, 8, 3], [300, 32, 16, 4], [275, 32, 8, 4], [225, 16, 16, 2]]
weights:  [0.25 0.25 0.25 0.25]
criterias:  [False, True, True, True]


In [25]:
calc_enthropy(input_matrix)

col_sum [[1250.  112.   60.   18.]]
entropy_matrix [[0.2        0.14285714 0.2        0.27777778]
 [0.16       0.14285714 0.13333333 0.16666667]
 [0.24       0.28571429 0.26666667 0.22222222]
 [0.22       0.28571429 0.13333333 0.22222222]
 [0.18       0.14285714 0.26666667 0.11111111]]
entropy_matrix [[-0.32188758 -0.27798716 -0.32188758 -0.35581496]
 [-0.29321303 -0.27798716 -0.26865374 -0.29862658]
 [-0.34250793 -0.35793228 -0.35246822 -0.33423942]
 [-0.3331081  -0.35793228 -0.26865374 -0.33423942]
 [-0.30866372 -0.27798716 -0.35246822 -0.24413606]]
diversification [[0.006249   0.03703883 0.02815035 0.02633299]]
weight_vector [[0.06391458 0.37883183 0.28792078 0.26933281]]


array([[0.06391458, 0.37883183, 0.28792078, 0.26933281]])