<a href="https://colab.research.google.com/github/uwtintres/robotic_surgeries/blob/main/Enthropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project is the work of Alina Saduova, CSS graduate student at UWT, Spring'21. This notebook illustrates the implementation of weight generation by Entropy, where the weights are calculated according to the degree of diversity of the input data among each attribute.

In [ ]:
import numpy as np

def calc_enthropy(evaluation_matrix):
  row_size = len(evaluation_matrix)
  col_size = len(evaluation_matrix[0])
  h = -0.621335
  entropy_matrix = np.empty(shape=(row_size, col_size))
  weight_vector = np.empty(shape=(1, col_size))
  diversification = np.empty(shape=(1, col_size))
  col_sum = np.empty(shape=(1, col_size))
  for j in range(col_size):
    cursum = 0
    for i in range(row_size):
      cursum += evaluation_matrix[i][j]
    col_sum[0, j] = cursum

  for i in range(row_size):
    for j in range(col_size):
      entropy_matrix[i,j] = evaluation_matrix[i][j] / col_sum[0, j]
  print("\nEntropy matrix:\n", entropy_matrix)

  for i in range(row_size):
    for j in range(col_size):
      entropy_matrix[i,j] = np.log(entropy_matrix[i,j]) * entropy_matrix[i,j]
  print("\nEntropy matrix:\n", entropy_matrix)

  for j in range(col_size):
    cur_col_sum = sum(entropy_matrix[:, j])
    diversification[0, j] = 1 - cur_col_sum * h
  print("\nDiversification: ", diversification)

  for j in range(col_size):
    weight_vector[0, j] = diversification[0, j] / sum(diversification[0, :])
  print("\nWeights: ", weight_vector)
  return weight_vector

This is a driver code for the Entropy testing, where the input is the Excel file with the data of the format like in TOPSIS. However, we pass only the input matrix without the weights and the criteria because they are not required for the weights analysis.

In [ ]:
import numpy as np
import pandas as pd 

filename = "TOPSIS with custom weights.xlsx"
sheetname = "Beginning"
xl = pd.read_excel(filename, sheet_name=sheetname)
xl = pd.read_excel(filename, sheet_name=sheetname, usecols=range(1, len(xl.columns)+1))

# initializing input matrix
input_matrix = xl.tail(n=len(xl.index) - 2).values.tolist()
print('input matrix: ', input_matrix)


input matrix:  [[1, 20, 100, 94], [4, 40, 30, 30], [5, 85, 90, 75], [7, 32, 600, 98], [3, 28, 800, 46], [8, 49, 1200, 15], [12, 56, 150, 68], [2, 71, 300, 23], [10, 66, 300, 57], [6, 79, 800, 83], [9, 10, 700, 39], [15, 18, 1000, 10]]
weights:  [0.6 0.2 0.1 0.1]
criterias:  [False, False, False, True]


In [ ]:
calc_enthropy(input_matrix)

col_sum [[  82.  554. 6070.  638.]]
entropy_matrix [[0.01219512 0.03610108 0.01647446 0.14733542]
 [0.04878049 0.07220217 0.00494234 0.04702194]
 [0.06097561 0.1534296  0.01482702 0.11755486]
 [0.08536585 0.05776173 0.09884679 0.15360502]
 [0.03658537 0.05054152 0.13179572 0.07210031]
 [0.09756098 0.08844765 0.19769357 0.02351097]
 [0.14634146 0.10108303 0.0247117  0.10658307]
 [0.02439024 0.12815884 0.04942339 0.03605016]
 [0.12195122 0.11913357 0.04942339 0.08934169]
 [0.07317073 0.14259928 0.13179572 0.13009404]
 [0.1097561  0.01805054 0.11532125 0.06112853]
 [0.18292683 0.03249097 0.16474465 0.01567398]]
entropy_matrix [[-0.05374048 -0.11990731 -0.06764322 -0.28215374]
 [-0.1473378  -0.18976789 -0.02624341 -0.14375271]
 [-0.17056594 -0.28760585 -0.06244108 -0.25166734]
 [-0.21006907 -0.16470347 -0.22874968 -0.28775915]
 [-0.1210283  -0.15086441 -0.2670843  -0.18960197]
 [-0.22705148 -0.21451602 -0.32046861 -0.08817292]
 [-0.28124087 -0.23166341 -0.09144511 -0.23862144]
 [-0.0905749

array([[0.25721555, 0.27003203, 0.20966741, 0.263085  ]])